### ISSUE TITLE
rename flushall to flushdb

### ISSUE THREAD

**Issue by borg286** [meitu/kvrocks#2]
For compatability with the redis protocol you should implement the flushdb command. Currently you do this functionality with a command called flushall.

**Comment by git-hulk** [comment]
@borg286 yeah, you're right, i would fix it soon, thanks~

**Comment by git-hulk** [comment]
fixed, https://github.com/meitu/kvrocks/commit/99fccfe5fef540568cb49667b415a652ca7de300
