### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by smartlee** [meitu/kvrocks#53]
cd src && make all
You need to run this command from the toplevel of the working tree.
make[1]: 进入目录“/root/kvrocks/src”

Hint: Fetching submodules from the remote
git submodule init
You need to run this command from the toplevel of the working tree.
make[1]: *** [SUBMODULES] 错误 1
make[1]: 离开目录“/root/kvrocks/src”
make: *** [all] 错误 2

**Comment by git-hulk** [comment]
@smartlee 在 kvrocks 这层目录编译，不要进入 src

**Comment by smartlee** [comment]
这个cd src && make all 是log 输出 我看了下Makefile 应该是git update那步出错 因为我编译机器上是不能连外网的
但又有另外一个问题
/root/kvrocks/external/jemalloc/src/background_thread.c:843：对‘dlsym’未定义的引用
/root/kvrocks/external/jemalloc/src/background_thread.c:843：对‘dlsym’未定义的引用
另外 问下有交流的微信群吗

**Comment by git-hulk** [comment]
@smartlee gmail 邮件私你，没有联网的没法编译，依赖没法下载，建议找一台联网机器编译
