### ISSUE TITLE
提个bug

### ISSUE THREAD

**Issue by smartlee** [meitu/kvrocks#62]
https://github.com/meitu/kvrocks/blob/2ff46ef91d47f37945354d3a9e77ad49f33c4ce0/src/redis_request.cc#L49
这地方不能return ok,否则可能会导致命令断流，解析出错，我这边可以稳定复现，只能break。

**Comment by git-hulk** [comment]
@smartlee 可以帮忙提供一下问题和复现步骤

**Comment by smartlee** [comment]
这个是在流量大的时候必定会出现，考虑一下发过来几百条这样的命令
*3$3set$1a$1a
*3$3set$1a中断第一次收结束，在Bulklen这地方返回OK，这个地方解析执行会返回错误
第二次开始$1a
*3$3set$1a$1a
*3$3set$1a$1a

我们测试的例子就是
*3
$7
PUBLISH
$18
__sentinel__:hello
$104 这个地方中断了 后面这104个字符这次没有收到，下次接受才能收到，但这个地方执行的话就会报错

**Comment by git-hulk** [comment]
感谢反馈~

**Comment by smartlee** [comment]
补充下 后续测试发现的问题
这个地方处理起来得非常小心，否则就出错，先纠正下上面的错误这个地方，我的修改成break也是有问题的，这些问题在流量小的时候可能都不存在，但是一个定时炸弹，在大流量的时候就出问题了。
* 首先 BulkLen，BulkData这个地方如果收不到数据，必须等libevent回调过来继续收，所以我上面说break，让它继续循环，其实一直会收不到数据，因为libevent底层在处理缓冲区时加锁，一直死循环导致一直无法填充底层的buffer,所以一直在while true里面卡住了，而且usleep一段时间再break也不行，所以最好的方法就是等libevent底层回调，但这个地方直接返回ok也是有问题的，因为无法正确处理是否正确处理了一次循环，还是等待下次继续处理，还是出错，比较好的方式是，Status里面应该加retry语义的字段类似linux的EAGAIN，上层再通过判断是否该retry来继续处理。
* 其次 如果是retry的情况，必须保留上次处理的context信息，比如上次处理SET A A这条请求，执行到SET的时候发现收不到数据了，那么tokens里面得保留SET这个记录，也就说Tokenize 这个函数进入必须要判断是否接着上次没收完的命令继续收，还是执行一个新的命令开始？这样Redis::Request这个class里面的变量都初始化为0是不对的，得在Tokenize判断，而判断的准则则是是否一个干净的状态进入。
* 再次 if (multi_bulk_len_ == 0) 这个地方我觉得应该退出，进入干净状态，否则依赖底层是否能收到数据来退出，commands_里面的命令可能尾部是不完整的。
* 最后BulkData 这个地方evbuffer_pullup(input, bulk_len_ + 2) 返回值不可预期，可能会导致返回与预期不一致的数据，最终导致解析出错，我觉得调用evbuffer_readln来判断len和bulk_len_是否相等更合适，指定\r\n返回的话，在没遇到\r\n的时候，libevent是不会返回任何数据的。
``` c
        line = evbuffer_readln(input, &len, EVBUFFER_EOL_CRLF_STRICT);
        if (!line || len <= 0) {
          return Status(Status::Retry, "BulkData Need more data... wait next loop....");
        }
        if (len != bulk_len_){
          std::cout<< "except len:" << bulk_len_ << " real len:"<< len<<std::endl;
          return Status(Status::NotOK, "Protocol error: except len:"+std::to_string(bulk_len_)+ "real len:"+ std::to_string(len));
        }
```

**Comment by git-hulk** [comment]
这个地方返回 Status::Again() 类似的状态就可以了，下次进来以及解析的 token 信息仍然不会消失

```c
          Util::Split(std::string(line, len), " \t", &tokens_);
          commands_.push_back(std::move(tokens_));
          state_ = ArrayLen;
```
这个是 Redis 支持 inline 协议

**Comment by git-hulk** [comment]
> 最后BulkData 这个地方evbuffer_pullup(input, bulk_len_ + 2) 返回值不可预期，可能会导致返回与预期不一致的数据，最终导致解析出错，我觉得调用evbuffer_readln来判断len和bulk_len_是否相等更合适，指定\r\n返回的话，在没遇到\r\n的时候，libevent是不会返回任何数据的。

Redis 是二进制安全的协议，也就是应该要能允许数据里面携带 `\r\n` 字符，所以直接获取 bulk_len + 2 才是对的，不能按照 \r\n 来判断

**Comment by smartlee** [comment]
> > 最后BulkData 这个地方evbuffer_pullup(input, bulk_len_ + 2) 返回值不可预期，可能会导致返回与预期不一致的数据，最终导致解析出错，我觉得调用evbuffer_readln来判断len和bulk_len_是否相等更合适，指定\r\n返回的话，在没遇到\r\n的时候，libevent是不会返回任何数据的。
> 
> Redis 是二进制安全的协议，也就是应该要能允许数据里面携带 `\r\n` 字符，所以直接获取 bulk_len + 2 才是对的，不能按照 \r\n 来判断

我意思是 evbuffer_pullup可能返回任何值 不一定是预期的值 我调试的时候 bulk_len_是 7 返回值值是2,因为buffer可能没那么多数据，那就要等待下次callback再取。redis 行为中 set a \r\n 再去get a 返回是\\r\\n,所以evbuffer_readln没问题

**Comment by git-hulk** [comment]
> > > 最后BulkData 这个地方evbuffer_pullup(input, bulk_len_ + 2) 返回值不可预期，可能会导致返回与预期不一致的数据，最终导致解析出错，我觉得调用evbuffer_readln来判断len和bulk_len_是否相等更合适，指定\r\n返回的话，在没遇到\r\n的时候，libevent是不会返回任何数据的。
> > 
> > 
> > Redis 是二进制安全的协议，也就是应该要能允许数据里面携带 `\r\n` 字符，所以直接获取 bulk_len + 2 才是对的，不能按照 \r\n 来判断
> 
> 我意思是 evbuffer_pullup可能返回任何值 不一定是预期的值 我调试的时候 bulk_len_是 7 返回字符串可能是9之内的任何值,因为buffer可能没那么多数据，那就要等待下次callback再取。redis 行为中 set a `\r\n` 再去get a 返回是`\\r\\n`,所以evbuffer_readln没问题

这个在 evbuffer_pullup 上一行代码对 buffer 的长度做了判断，所以应该没有问题

**Comment by karelrooted** [comment]
> 这个是在流量大的时候必定会出现，考虑一下发过来几百条这样的命令
> *3$3set$1a$1a
> *3$3set$1a中断第一次收结束，在Bulklen这地方返回OK，这个地方�解析执行会返回错误
> 第二次开始$1a
> *3$3set$1a$1a
> *3$3set$1a$1a
> 
> 我们测试的例子就是
> *3
> $7
> PUBLISH
> $18
> **sentinel**:hello
> $104 这个地方中断了 后面这104个字符这次没有收到，下次接受才能收到，但这个地方执行的话就会报错

这个地方的重现步骤有没有什么重现的代码程序方式之类的提供一下？我试了用redis-benchmark及在线上查了一批日志，重现不了这种错误，错误是INFO日志里面有这种信息“Failed to tokenize the request, encounter error:” ？

代码里判定了若  multi_bulk_len_ ==0 才会将 tokens_ 赋值给 commands_, 所以理论上 只收到一部分，返回OK是不会触发执行一部分的命令的，会在后续的OnRead event中等完整的命令信息接收完毕，才会执行那条完整的命令

**Comment by smartlee** [comment]
> > 这个是在流量大的时候必定会出现，考虑一下发过来几百条这样的命令
> > *3$3set$1a$1a
> > *3$3set$1a中断第一次收结束，在Bulklen这地方返回OK，这个地方�解析执行会返回错误
> > 第二次开始$1a
> > *3$3set$1a$1a
> > *3$3set$1a$1a
> > 我们测试的例子就是
> > *3
> > $7
> > PUBLISH
> > $18
> > **sentinel**:hello
> > $104 这个地方中断了 后面这104个字符这次没有收到，下次接受才能收到，但这个地方执行的话就会报错
> 
> 这个地方的重现步骤有没有什么重现的代码程序方式之类的提供一下？我试了用redis-benchmark及在线上查了一批日志，重现不了这种错误，错误是INFO日志里面有这种信息“Failed to tokenize the request, encounter error:” ？
> 
> 代码里判定了若 multi_bulk_len_ ==0 才会将 tokens_ 赋值给 commands_, 所以理论上 只收到一部分，返回OK是不会触发执行一部分的命令的，会在后续的OnRead event中等完整的命令信息接收完毕，才会执行那条完整的命令

我这边是在实现同步redis作为master的实现的时候发现的，实现上跟代码里现有的有区别，仔细看了下原来的逻辑，的确是return ok不会导致报错，为了防止万一 我不复用这个函数，重复写个类似的 来接受master的命令，原来的逻辑保持原样 ，看看能不能复现，但愿是我不小心误用。
