### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by smartlee** [meitu/kvrocks#64]
运行一段时间经常会段错误，抓了core看了下，可能问题是在evbuffer_drain这里面，
chain这个地方为空指针取值了，网上搜了下，指出bufferevent_socket_new 的时候要加BEV_OPT_THREADSAFE，猜测可能是这个问题。
![image](https://user-images.githubusercontent.com/1262498/76509672-5bb45c80-648b-11ea-94f2-8ab361b75050.png)

**Comment by git-hulk** [comment]
这个看起来不是 kvrocks 的堆栈来着

**Comment by smartlee** [comment]
的确是kvrocks的堆栈
![image](https://user-images.githubusercontent.com/1262498/76520003-fe290b80-649c-11ea-9027-93be85831c61.png)

**Comment by git-hulk** [comment]
可以执行一下 bt, 贴一下

**Comment by smartlee** [comment]
![image](https://user-images.githubusercontent.com/1262498/76584381-bb0b7e80-6516-11ea-9d8f-25b1c74ac691.png)

**Comment by git-hulk** [comment]
这个是你修改过的代码吧？kvrocks 的连接是线程内独占的，不会有 data race，另外这个堆栈看起来是修改过的代码。

**Comment by smartlee** [comment]
worker这边我没有动过 我是改了master-repl  线程的代码

**Comment by smartlee** [comment]
看了十几个core文件 发现了问题 的确是我们改的代码引起的  改的代码引出同步redis 的线程，但这个线程在命令传播阶段会偶尔跟处理客户端的线程访问同一个evbuffer  非常奇怪

**Comment by git-hulk** [comment]
恩，kvrocks 里面的连接都是线程内的，不会有 data race，你那边设计上也需要调整一下
